'*.{js,jsx,ts,tsx}': ['eslint --fix', 'prettier --write']
'{!(package)*.json,*.code-snippets,.!(browserslist|cz)*rc}':
  ['prettier --write--parser json']
'package.json': ['prettier --write']
'*.html': ['prettier --write']
'*.md': ['prettier --write']