/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'client_index': RouteRecordInfo<'client_index', '/', Record<never, never>, Record<never, never>>,
    'not-found': RouteRecordInfo<'not-found', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'admin_index': RouteRecordInfo<'admin_index', '/admin', Record<never, never>, Record<never, never>>,
    'admin_layer_1': RouteRecordInfo<'admin_layer_1', '/admin/layer-1', Record<never, never>, Record<never, never>>,
    'admin_layer_1-1': RouteRecordInfo<'admin_layer_1-1', '/admin/layer-1', Record<never, never>, Record<never, never>>,
    'admin_layer_1-2': RouteRecordInfo<'admin_layer_1-2', '/admin/layer-1/layer-1-2', Record<never, never>, Record<never, never>>,
  }
}
